### ISSUE TITLE
Swift 5.3 support

### ISSUE THREAD

**Issue by noobd3veloper** [verifidentity/Cloudcheck-iOS-SDK-Framework#1]
Upon Compiling app ung latest xcode, an exception is return.

module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3.2 compiler

![image](https://user-images.githubusercontent.com/26892245/103184530-9a6cb380-48f3-11eb-9b86-a47d538fd893.png)

**Comment by TomCarey** [comment]
@noobd3veloper I've rebuilt it for you. Try pull from master and let me know how it goes
